### ISSUE TITLE
model

### ISSUE THREAD

**Issue by yyfyan** [HongyangGao/ChannelNets#1]
Can you provide the trained-model? thank you!

**Comment by HongyangGao** [comment]
Hi there,

This a trained model link: https://drive.google.com/file/d/1DGaFVL6dgvkPxyyEfMlKYp5zgseHebWY/view?usp=sharing
https://drive.google.com/file/d/1Z4jqTA9850f6VGlfVU2R-3zpJz1Xjn8z/view?usp=sharing
I am not sure if it is the best performance as reported in the paper. But it should be around it. Have you try to train the model by yourself?

**Comment by yyfyan** [comment]
No,because I have only one GPU.

**Comment by HongyangGao** [comment]
OK, one GPU will not work since the batch size should be at least 512.
