### ISSUE TITLE
FLOPs of ChannelNets-v2 and v3?

### ISSUE THREAD

**Issue by iamhankai** [HongyangGao/ChannelNets#3]
Could you provide the FLOPs of ChannelNets-v2 and v3?

**Comment by HongyangGao** [comment]
ChannelNets-v2 and v3 are for parameter reduction but not for reducing FLOPS. If you really need, I can calculate them for you.

**Comment by iamhankai** [comment]
> ChannelNets-v2 and v3 are for parameter reduction but not for reducing FLOPS. If you really need, I can calculate them for you.

Yes, I need them for comparison in my paper. I'll cite your work :)

**Comment by HongyangGao** [comment]
WOW, thanks. I will calculate them and give you results later.

**Comment by HongyangGao** [comment]
Hi, FLOPS of V2 and V3 are 361m and 360m, respectively. Thanks.

**Comment by iamhankai** [comment]
Thank u very much!
