### ISSUE TITLE
How do I use your code？

### ISSUE THREAD

**Issue by YuanGao-cs** [HongyangGao/ChannelNets#4]
Hello, I am very interested in your work, and I would like to repeat your results.How do I use your code？

**Comment by HongyangGao** [comment]
Hi there,

Currently the configuration in main.py in for ChannelNet V1. The batch size I use is 512, which means you can use batch size 64 with 8 gpus or 128 with 4 gpus. You will need tensorflow and tensorpack.

Hongyang
